<a href="https://colab.research.google.com/github/josefl19/cursoPythonInnov/blob/main/sesiones/parteDos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Curso de Python (parte 2)

## Listas y tuplas

Una **colección** es un conjunto de elementos que se agrupan en una sola estructura de datos de Python. De manera nativa Python tiene soporte para:
- Listas y tuplas
- Diccionarios y conjuntos
- ¿Otros?

#### Ejemplo:

```python
lista = [1.0, 2.0, 3.0]
tupla = (1.0, 2.0, 3.0)
diccionario = {
    "day": 6,
    "month": "August"
}
```

- Las listas y tuplas tienen un índice asociado.
- Las listas y tuplas tienen una longitud (número de elementos) asociado.
- Se puede hacer slicing.

In [2]:
lista_tacos = [
    "chorizo",  #0
    "bistek",   #1
    "pastor",   #2
    "tripas",   #3
    "cabeza",   #4
    "lengua"    #5
]
print(lista_tacos)

['chorizo', 'bistek', 'pastor', 'tripas', 'cabeza', 'lengua']


In [2]:
#Acceder a una posición de la lista
print(lista_tacos[2])
print(lista_tacos[5])

pastor
lengua


In [5]:
# Obtener el tamaño de la lista (numero de elementos)
print(len(lista_tacos))

6


In [6]:
print(lista_tacos[5])
lista_tacos[5] = "combinado"
print(lista_tacos[5])

lengua
combinado


In [7]:
# Manejo de tuplas
tuplas_tacos = (
    "chorizo",  #0
    "bisteck",  #1
    "pastor",   #2
    "papa",     #3
    "cabeza",   #4
    "lengua",   #5
    "cesos"     #6
)

print(tuplas_tacos[2])

pastor


In [8]:
#Las tuplas son INMUTABLES (no se puede cambiar su valor)
print(tuplas_tacos[2])
tuplas_tacos[2] = "pastor con piña"
print(tuplas_tacos[2])

pastor


TypeError: ignored

In [9]:
# [inicio:fin - 1:salto] <-- Slicing! (Rebanado)
print(lista_tacos)
print(lista_tacos[0:len(lista_tacos):2])
print(lista_tacos[1:3 + 1])

['chorizo', 'bistek', 'pastor', 'tripas', 'cabeza', 'combinado']
['chorizo', 'pastor', 'cabeza']
['bistek', 'pastor', 'tripas']


In [1]:
m = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

print(m)

# Spoiler
import numpy as np
print(np.array(m))

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Condicionales II

Los condicionales los utilizaremos para validar si se cumple una o más condiciones para ejecutar cierto bloque de código, **incluso para validar si algúin dato forma parte de una colección**.

#### Ejemplo:

```python
>>> 1 in [1, 2, 3, 4, 5]
```

In [4]:
print(lista_tacos)
"chorizo" in lista_tacos

['chorizo', 'bistek', 'pastor', 'tripas', 'cabeza', 'lengua']


True

In [6]:
tipo_taco = "pastor"
if tipo_taco in lista_tacos:
  print("Si hay tacos")
else:
  print("No hay tacos")

Si hay tacos


## Ciclo `for`

Python tiene un ciclo basado en colecciones o en iteradores. Este tipo de ciclo itera sobre una colección de objetos, en lugar de especificar valores o condiciones numéricos, este ciclo se llama ciclo for.

#### Sintaxis:

```python
for element in collection:
    # Block of code that iterates over the collection
```

Ejemplo en lenguaje C:

```c
for (int i=0; i < 100; i++) {
    // Ciclo
}
```

In [8]:
print(lista_tacos)

for taco in lista_tacos:
  guiso = taco.upper()
  print(guiso) 

['chorizo', 'bistek', 'pastor', 'tripas', 'cabeza', 'lengua']
CHORIZO
BISTEK
PASTOR
TRIPAS
CABEZA
LENGUA


In [11]:
list(range(1, 11))

for i in range(len(lista_tacos)):
  print(lista_tacos[i])

chorizo
bistek
pastor
tripas
cabeza
lengua


In [13]:
lenguajes = [
    "C",
    "Java",
    "C++",
    "C#",
    "Dart",
    "SQL",
]

print(lenguajes)

['C', 'Java', 'C++', 'C#', 'Dart', 'SQL']


In [14]:
lenguajes.append("Python") #Añadir elemento a la lista
print(lenguajes)

['C', 'Java', 'C++', 'C#', 'Dart', 'SQL', 'Python']


In [15]:
for i in range(5):
    print((i + 1) * "*")

*
**
***
****
*****


In [20]:
perritoz = [
    "https://i.pinimg.com/originals/70/fa/97/70fa97bac09e524bae4c006a1ead5512.jpg",
    "https://i.pinimg.com/originals/21/c1/13/21c113e05f1a219989a0b07a03b1577a.jpg",
    "https://i.pinimg.com/originals/63/96/0c/63960c5db954115a0b5d8868c0c7e8a0.jpg"
]

from IPython.display import Image
Image(url=perritoz[0])

## Funciones (pt. I)

La manera en la que empaquetamos procesos que ejecutan un bloque completo de código es a través de funciones, la sintaxis de Python es muy sencilla y eficiente para escribir bloques de código de forma ordenada.

La mayoría de los paquetes en Python están conformados por objetos y funciones.

#### Sintaxis:

```python
def function_name(arguments):
    # Block of code
	# Final block of code
	return something
```

In [21]:
def F(masa):
    # 2da. Ley de Newton
    # F = ma

    a = 9.81
    fuerza = masa * a
    print(fuerza)

In [22]:
F(10)
F(55)
F(83)

98.10000000000001
539.5500000000001
814.23


In [23]:
def segunda_de_Newton(masa, aceleracion):
    fuerza = masa * aceleracion
    return fuerza

In [24]:
segunda_de_Newton(10, 9.81)

98.10000000000001